[buildPlans.pragmasevka]
family = "Pragmasevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

    [buildPlans.pragmasevka.widths.normal]
    shape = 500
    menu  = 5
    css   = "normal"

    [buildPlans.pragmasevka.metricOverride]
    leading = 1100
    xHeight = 550
    periodSize = 'blend(weight, [425, default_periodSize * 1.2], [800, default_periodSize * 1.1])'

    [buildPlans.pragmasevka.ligations]
    inherits="dlig"
    disables = ["slash-asterisk"]

    [buildPlans.pragmasevka.variants]
    inherits = "ss08"

    [buildPlans.pragmasevka.weights.regular]
    shape = 425
    menu = 400
    css = 400

    [buildPlans.pragmasevka.weights.bold]
    shape = 800
    menu = 700
    css = 700

    [buildPlans.pragmasevka.slopes]
    upright = "default.Upright"
    italic = "default.Italic"

[buildPlans.pragmasevka-mono]
family = "Pragmasevka Mono"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

    [buildPlans.pragmasevka-mono.widths.normal]
    shape = 500
    menu  = 5
    css   = "normal"

    [buildPlans.pragmasevka-mono.metricOverride]
    leading = 1100
    xHeight = 550
    periodSize = 'blend(weight, [425, default_periodSize * 1.2], [800, default_periodSize * 1.1])'

    [buildPlans.pragmasevka-mono.ligations]
    inherits = "dlig"
    disables = ["slash-asterisk"]

    [buildPlans.pragmasevka-mono.variants]
    inherits = "ss08"

    [buildPlans.pragmasevka-mono.weights.regular]
    shape = 425
    menu = 400
    css = 400

    [buildPlans.pragmasevka-mono.weights.bold]
    shape = 800
    menu = 700
    css = 700

    [buildPlans.pragmasevka-mono.slopes]
    upright = "default.Upright"
    italic = "default.Italic"
